### ISSUE TITLE
 Fork Link Broken on Canvas

### ISSUE THREAD

**Issue by horaciovelvetine** [learn-co-curriculum/selection-sort#1]
### Canvas Link

https://learning.flatironschool.com/courses/4831/assignments/141069?module_item_id=294733

### Concern

Hey! The link for forking the lesson seems to be broken, GH repo link works great!

**Comment by graciemcguire** [comment]
Hello @horaciovelvetine! Thanks for submitting this issue.
The fork link may not have been working because of a server error, and isn't something we can change on our end. (This is likely why the github link was still working! 😄) 

I'm going to go ahead and close this issue, but if you think I've closed the issue in error please reopen and we will take another look!
